export const MAX_WALK_TO_TRANSIT_DISTANCE_KM = 0.7;
export const TRANSIT_ACCESS_DISTANCE_RATIO = 0.15;
export const DEFAULT_TRANSIT_SPEED_KMH = 24;
export const MIN_TRANSIT_LEG_MINUTES = 5;
export const DEFAULT_TRANSIT_WAIT_MINUTES = 6;
